print("Enter the length of the rectangle:")
a=float(input())
print("Length of rec is:",a)
print("Enter the breadth of the rectangle:")
br=float(input())
print("Breadth of rec is:",br)
ar= (a)* (br)
print("Area of rec is:",ar)
